version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: homelab-auth-db-dev
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - homelab-auth-network
    restart: unless-stopped

volumes:
  postgres_dev_data:


networks:
  homelab-auth-network:
    driver: bridge
